library(levenR)
if(reverseString('123')!='321')stop(simpleError('Reverse strings not correct'))
if(complimentDna('TTACCCG')!='AATGGGC')stop(simpleError('Compliment DNA incorrect'))
if(revComp('TTACCCG')!=complimentDna(reverseString('TTACCCG')))stop(simpleError('revComp not equal reverse and compliment'))
if(revComp('TTACCCG')!=reverseString(complimentDna('TTACCCG')))stop(simpleError('revComp not equal reverse and compliment'))
if(revComp('TACCG')!='CGGTA')stop(simpleError('revComp not correct'))
if(leven('AAA','AAA')!=0)stop(simpleError('Equal strings not equal'))
if(leven('AT','A')!=1)stop(simpleError('Difference between AT and A not 1'))
if(leven('A','AT')!=1)stop(simpleError('Difference between A and AT not 1'))
if(leven('A','T')!=1)stop(simpleError('Difference between A and T not 1'))
if(leven('asdasdasedaeswaseaseasdasdfdfsdfgdfgsdfsdfaeruiurtyuuiyuyiuvdyiuyiuyiuyiuyiuyiuyiuyasduifysaiyufasiyudfaisyufiasyufisayufiasyufisayfisayufsaiyufisaydfiasyufiasydfiasyfisaydfiasyisayfisyisaiuyyiauyriutryiuayiuyiuyiuyiuyiuyiuyiuyiuadfuasduyasfiuysadufyaisydfiuaysfiyiuyiuaydfiasydfiasyayyig','asdasdasedaeswaseaseasdasdfdfsdfgdfgsdfsdfaeruiurtyuuiyuyiuvdyiuyiuyiuyiuyiuyiuyiuyasduifysaiyufasiyudfaisyufiasyufisayufiasyufisayfisayufsaiyufisaydfiasyufiasydfiasyfisaydfiasyisayfisyisaiuyyiauyriutryiuayiuyiuyiuyiuyiuyiuyiuyiuadfuasduyasfiuysadufyaisydfiuaysfiyiuyiuaydfiasydfiasyayyig')!=0)stop(simpleError('Equal longer strings not equal'))
if(all(leven(c('AAAA','AA'),'AAA')!=1))stop(simpleError('Multiple string1 do not produce expected'))
if(all(leven('AAA',c('AAAA','AA'))!=1))stop(simpleError('Multiple string2 do not produce expected'))
if(tryCatch(leven(NULL,'AAA'),error=function(x)"Caught error")!='Caught error')stop(simpleError('Did not catch NULL input'))
if(all(unlist(levenAlign('AA','AA'))!=c('AA','AA')))stop(simpleError('Aligning AA and AA does not produce AA and AA'))
if(all(unlist(levenAlign('AAT','AA'))!=c('AA-','AAT')))stop(simpleError('Aligning AAT and AA does not produce AAT and AA-'))
if(all(unlist(levenAlign('AATC','AAC'))!=c('AA-C','AATC')))stop(simpleError('Aligning AATC and AAC does not produce AATC and AA-C'))
if(all(unlist(levenAlign('AAC','AATC'))!=c('AATC','AA-C')))stop(simpleError('Aligning AAC and AATC does not produce AA-C and AATC'))
if(all(unlist(levenAlign('TAAAAAATC','AAATC'))!=c('-AAA---TC','TAAAAAATC')))stop(simpleError('Aligning TAAAAAATC and AAATC does not produce -AAA---TC and TAAAAAATC'))
if(all(unlist(levenAlign(c('TAA','AAT'),'AA'))!=c('-AA-','TAA-','-AAT')))stop(simpleError('Aligning TAA,AAT and AA does not produce TAA-,-AAT and -AA-'))
if(all(combineAligns(c('AAT','AA','T','AAT'),c('AAT','AT','T','--T'),c(1:3,1))!=c('AAT','.AT','..T','--T')))stop(simpleError('Combining alignments with starts does produce expected'))
if(all(unlist(levenAlign('AAAAACTTT','AAC',trimOuterGaps=TRUE,substring1=TRUE))!=c('AAC','AAC')))stop(simpleError('Trim outer gaps and substrings incorrect'))
if(all(unlist(levenAlign('AAC','AAAAACTTT',trimOuterGaps=TRUE,substring2=TRUE))!=c('AAC','AAC')))stop(simpleError('Trim outer gaps and substrings incorrect'))
if(leven('AAA')!=0)stop(simpleError('leven on self did not return 0'))
if(all(dim(leven(c('AAA','ATA')))!=c(2,2)))stop(simpleError('leven on 2 seqs did not produce 2x2 matrix'))
if(all(leven(c('AAA','ATA','ATA'),c('AAA','ATA','ACA'),oneToOne=TRUE)!=c(0,0,1)))stop(simpleError('One to one leven incorrect'))
if(all(leven(c('AA','AT','TA'),c('XXAAA','XXATA','XXACA'),oneToOne=TRUE,substring2=TRUE)!=c(0,0,1)))stop(simpleError('Substring leven incorrect'))
if(all(leven(c('AAAA','ATAA','AAATA'),c('AAA','ATA','ACA'),oneToOne=TRUE,substring1=TRUE)!=c(0,0,1)))stop(simpleError('Substring leven incorrect'))
if(all(leven(c('AAAA','ATAA','AAATA','XXX'))!=leven(c('AAAA','ATAA','AAATA','XXX'),nThreads=3)))stop(simpleError('Multithreading produces incorrect results'))
